### ISSUE TITLE
WIP: Berliner 0.0.5

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/berliner#10]
Berliner 0.0.5 will focus on code health and a minimum viable feature set.

Fetching
-----------
- [x] Separate source feed scraping from source parsing
- [x] Support aggregators
- [x] Stress test Feedjira RSS scraper
- [x] Figure out encoding issues. Everything should be `utf-8` all the way through

Parsing
----------
- [x] Decide whether to bundle `Nokogiri`

Filtering
-----------
- [x] Implement filter options
- [x] Resolve filter types and/or paging conversation
- [ ] Add sections

Sources
-----------
- [ ] Add post types?

Articles
----------
- [ ] Lock down fields
- [x] Add `via` field

Rendering
-------------
- [x] Figure out where to put CSS

Config
--------
- [x] Figure out how to represent filter chains with options
- [x] Figure out how to extend profile by options/defaults, without writing options/defaults back to disk

Refactoring
---------------
- [x] If managers don't change, make DRY-er
- [x] Extend string with `slugify` method
- [x] Extend string with `deslugify` method

CLI
----
- [x] Add logging module, no `puts`
- [ ] Figure out how to represent renderers
- [ ] Figure out how to represent filters
- [x] Add global options (like `verbosity`)

Code Health
----------------
- [x] Add [Rubocop](https://github.com/bbatsov/rubocop)
- [x] Follow style guide
- [x] Add service (Code Climate)

Testing
----------
- [ ] Add spec for all functions
- [ ] Add shared examples for all filters, sources, and renderers
- [ ] Add CLI tests
- [ ] 100% code coverage

Other
-------
- [x] Decide where to save Berliners
- [ ] Decide whether to implement caching
- [x] Move communications to [Gitter](https://gitter.im/)
