### ISSUE TITLE
Planning: Berliner 0.1.0

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/berliner#11]
Berliner 0.1.0 will target a stable API, relative feature-richness, a codebase ready for external contributors, a product ready for the general public, and an ecosystem of many sources/filters/renderers.

Website
----------
- [ ] Design and deploy [http://berliner.io](http://berliner.io)

UX
----
- [ ] Pretty print status and progress to stdout

Filtering
----------
- [ ] Add 5 filters

Sources
----------
- [ ] Add 20 sources
- [ ] Add 5 aggregators

Refactoring
---------------
- [ ] Make dependency graph and eliminate unnecessary edges
- [ ] Write separate downloads queue which handles all parallelization.

Rendering
--------------
- [ ] Run HTML through [RubyPants](https://github.com/jmcnevin/rubypants) for better web typography
- [ ] Content-aware image cropping #15 
- [ ] Design more than one renderer

Code Health
----------------
- [ ] Design decisions, diagrams, and references detailed in [thorough, descriptive comments](https://news.ycombinator.com/item?id=8826839)

Distribution
---------------
- [ ] Updating? Does this break gem compatibility??

CLI
----
- [ ] Re-evaluate help text output
