### ISSUE TITLE
Decide where to track first milestone

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/berliner#52]
Proposed work items:
- [ ] All sources that ship with Apple News (or some similar list of 10-20 big publishers)
- [ ] Sanitized HTML
- [ ] HTML as IR (whitelist a subset of tags)
- [ ] Proper support for images (validation + knowledge of dimensions)
- [ ] Proper differentiation between source & via fields
- [ ] Effective ranking system
- [ ] Filter to rank posts by feed frequency
- [ ] Filter to rank by some popularity method (if Twitter is too difficult, do something else for MVP)
- [ ] Some metadata filter (add author images?)
- [ ] Filter utility for users to write custom field + condition filters (e.g. `f.Reject(func (p content.Post) bool {})`)
- [ ] Simple, bootstrap based smart renderer
    - [ ] Post with many images yields gallery
    - [ ] Image dimensions determine whether image is header or sidebar
    - [ ] Renderer separates intelligently into post types
- [ ] Intelligent CLI output for messages/errors
- [ ] caching of all network requests
- [ ] Correct de-duping filter
- [ ] Unit tests where applicable
- [ ] Somewhat polished README.md

@geoffreylitt WDYT?  Where should we track these?

**Comment by geoffreylitt** [comment]
Looks about right to me. Only edit I would make is to focus on sources we want in our Berliners before "famous sources". I think the heuristic for what to work on right now should be "what is the biggest thing preventing me from having a Berliner I want to use every day"

I made issues and a [milestone](https://github.com/s3ththompson/berliner/milestones/Alpha)

**Comment by s3ththompson** [comment]
@geoffreylitt makes sense.  Feel free to edit the source issue.  Going to close this issue now that we have a milestone, and a set of issues to track in waffle
